language: python
jobs:
  include:
    - name: "Windows Lint"
      os: windows
      language: sh
      python: "3.7"
      cache: pip
      before_install:
        - choco install python --version 3.7.3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - pip install pylint
      script:
        - pylint library queries application interface python_voice_coding_plugin.py
